// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAnRQTndHXJ1UbB9aQCmbmXC41Cav6dOM',
    appId: '1:915983334116:web:c1499bf96ff06c7d7f0af1',
    messagingSenderId: '915983334116',
    projectId: 'lifelog-7aff9',
    authDomain: 'lifelog-7aff9.firebaseapp.com',
    storageBucket: 'lifelog-7aff9.firebasestorage.app',
    measurementId: 'G-9HXC8E9C5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpeQHUTBtTp63TQdOQw33_WX3JVp9ZvHc',
    appId: '1:915983334116:android:28d411ce456409a97f0af1',
    messagingSenderId: '915983334116',
    projectId: 'lifelog-7aff9',
    storageBucket: 'lifelog-7aff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0f6cWZEhewl7828SXBYzeFmzxUhFzsiA',
    appId: '1:915983334116:ios:68a24ecc69b826797f0af1',
    messagingSenderId: '915983334116',
    projectId: 'lifelog-7aff9',
    storageBucket: 'lifelog-7aff9.firebasestorage.app',
    iosBundleId: 'com.example.lifeLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0f6cWZEhewl7828SXBYzeFmzxUhFzsiA',
    appId: '1:915983334116:ios:68a24ecc69b826797f0af1',
    messagingSenderId: '915983334116',
    projectId: 'lifelog-7aff9',
    storageBucket: 'lifelog-7aff9.firebasestorage.app',
    iosBundleId: 'com.example.lifeLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAnRQTndHXJ1UbB9aQCmbmXC41Cav6dOM',
    appId: '1:915983334116:web:9985a6ea5be911517f0af1',
    messagingSenderId: '915983334116',
    projectId: 'lifelog-7aff9',
    authDomain: 'lifelog-7aff9.firebaseapp.com',
    storageBucket: 'lifelog-7aff9.firebasestorage.app',
    measurementId: 'G-9J9JGKT7R3',
  );
}
